### ISSUE TITLE
Undefined array key 0 in includes/classes/categories_ul_generator.php on line 50

### ISSUE THREAD

**Issue by bumerang24** [zencartpro/zencart-german-grundsystem#14]
[25-Aug-2022 17:07:40 Europe/Berlin] Request URI: /index.php?main_page=index&cPath=1_7_30, IP address: 114.
#1 zen_categories_ul_generator->buildBranch() called at [/includes/classes/categories_ul_generator.php:75]
#2 zen_categories_ul_generator->buildTree() called at [/includes/templates/responsive_classic/templates/tpl_modules_mobile_menu.php:58]
#3 require(/includes/templates/responsive_classic/templates/tpl_modules_mobile_menu.php) called at [/includes/templates/responsive_classic/common/tpl_main_page.php:257]
#4 require(/includes/templates/responsive_classic/common/tpl_main_page.php) called at [/index.php:95]
--> PHP Warning: Undefined array key 0 in /includes/classes/categories_ul_generator.php on line 50.

**Comment by webchills** [comment]
Generell: völlig harmlose Warning, keinerlei Funktionsproblem
Hier wird anscheinend ein komplett leerer Shop ohne jede Kategorie, ohne jeden Artikel mit einem Smartphone aufgerufen.
Diese Warning wird verschwinden, sobald eine Kategorie angelegt wurde.

**Comment by bumerang24** [comment]
Danke dir. Das hatte ich unteranderen auch im Live Shop so, deshalb habe ich jetzt den Shop schon zum sechsten Mal leer installiert.

**Comment by webchills** [comment]
not a bug

**Comment by bumerang24** [comment]
Passt, alles klar Danke dir
