### ISSUE TITLE
Die Summenkalkulationen stimmen nicht mehr

### ISSUE THREAD

**Issue by aurixan** [zencartpro/zencart-german-grundsystem#15]
Die Summenbildung in den Bestell Details in zencart V1.5.7e stimmt nicht mehr. Vorher hatte ich zencart 1.5.6f. Da schien noch alles ok.
![Bestell_Details](https://user-images.githubusercontent.com/79226766/195440090-2f355807-dd80-4345-8925-481677faf087.jpg)

Die Zwischensumme zeigt einen falschen Wert, der nicht ser Summe der darüberliegenden Zahlen entspricht

**Comment by aurixan** [comment]
Die Mehrwertsteuer wird auch nicht richtig berechnete. Anbei zur Vereinfachung ein Beispiel für eine Rechnung von 10 gekauften 10 EUR Artikeln (SUMME SOLL: 100 EUR) mit 20% Mehrwertsteuer (SOLL: 20 EUR):
![100EUR-20EUR](https://user-images.githubusercontent.com/79226766/195506127-99396af8-ca02-43ed-8363-67299dbfdc4f.jpg)

**Comment by aurixan** [comment]
Vereinfachtes Beispiel aus dem Testshop mit 10 x einem 10EUR Artikel und 20% MWST (nicht auf Shipping):
![image](https://user-images.githubusercontent.com/79226766/195512719-f4168f6f-52ff-4bd1-b08d-aa0d820e3c6e.png)

**Comment by aurixan** [comment]
Vereinfachtes Beispiel mit 10x 10EUR-Arktikel: 
![100EUR-20MWST-nicht auf shipping](https://user-images.githubusercontent.com/79226766/195513724-ea52c93f-a51c-4a0c-b3d8-de473e025479.jpg)

**Comment by aurixan** [comment]
Der Admin sieht die gleiche Bestellung der 10x 10EUR Artikel anders:
![100EUR-20MWST-nicht auf shipping_admin](https://user-images.githubusercontent.com/79226766/195514283-0bc013f5-33b6-4a3d-8cc5-0376d423263b.jpg)

**Comment by webchills** [comment]
Für manche Szenarien ist die folgende Rundung nicht für alle Preise passend:
includes/classes/order.php
ca. Zeile 447:
`'final_price' => zen_round($products[$i]['price'] + $_SESSION['cart']->attributes_price($products[$i]['id']), $decimals),`
Ändere das auf:
`'final_price' => $products[$i]['price'] + $_SESSION['cart']->attributes_price($products[$i]['id']),`
Damit sind Deine beiden Beispiele dann OK

**Comment by webchills** [comment]
Standardmäßige Rundung entfernt, Rundungsfunktion optional für Shopkonfigurationen, bei denen die alte Funktion besser passt.
siehe 543ca95

**Comment by aurixan** [comment]
> Standardmäßige Rundung entfernt, Rundungsfunktion optional für Shopkonfigurationen, bei denen die alte Funktion besser passt. siehe [543ca95](https://github.com/zencartpro/zencart-german-grundsystem/commit/543ca95cca0e3f838847ceb2d53ec1a41703faa9)

DANKE. Ich habe es kurz in verschiedenen Szenarien getestet. Jetzt funktioniert es wieder.

**Comment by aurixan** [comment]
Hallo Jörg,

mein web Hoster stellt Ende November von php 8.0 auf php 8.2 um (Host Europe).
Wird es bis dahin noch eine zen cart pro Release geben, die php 8.2 unterstützt?

Gruss aus München
Aurixan (Kay)

**Comment by webchills** [comment]
Host Europe wird PHP 8.1 erst Ende November 2024 abschalten, es gibt auch vorher gar keinen Grund dafür.
Bei der Umstellung Ende November 2023 geht es um PHP 8.0
Es gibt in der aktuellen deutschen Zen Cart Version 1.5.7f nur noch sehr wenige Dateien, die noch nicht vollständig auf PHP 8.1 optimiert sind. Sie wird daher auch mit PHP 8.1 funktionieren, es kann dabei lediglich zu einigen Warning Logs mehr kommen. Ein letztes Update für 1.5.7 wird es noch in diesem Jahr geben. Diese Version 1.5.7g wird dann auch 100% mit PHP 8.1. funktionieren.
Aktiviere bei HostEurope die Verlängerung von PHP 8.0 bis Ende November und betreibe den Shop erstmal weiter mit PHP 8.0
Sobald 1.5.7g released ist, kannst Du dann das Update einspielen und auf PHP 8.1 stellen.
Eine vollständige Unterstützung von PHP 8.2 wird es erst mit 1.5.8 deutsch geben, das im Laufe des nächsten Jahres erscheinen wird.

**Comment by aurixan** [comment]
Vielen Dank für die Info.
