### ISSUE TITLE
Summen im Verkaufsbericht stimmen nicht mehr

### ISSUE THREAD

**Issue by aurixan** [zencartpro/zencart-german-grundsystem#16]
Die Summne im Verkaufsbericht (zc 1.5.7e) scheinen mir nicht schlüssig, ich werde das später noch genauer ausführen:
![Verkaufsbericht](https://user-images.githubusercontent.com/79226766/195441906-de1e6ee4-38ab-4e50-a769-3bdaf78caabc.jpg)

**Comment by aurixan** [comment]
Das Problem ist, dass das TOTAL im Verkaufsbericht zu hoch ist, und zwar um genau den Betrag der Mehrwertsteuer für die Versandkosten (Butto = 6 EUR, Netto = 5 EUR @ 20% MwSt)
Das TOTAL müsse 10 x 10€ + 6€ = 106 EUR sein (Nicht 107 EUR).
![image](https://user-images.githubusercontent.com/79226766/195551914-bddb7a1a-0d4f-4592-8d76-c2a1751471ae.png)

In dem Beispiel aus dem ersten Post sehen wir das gleiche Problem:
Die MwSt beträgt 19% auf alle Waren und Versandkosten.

SUMME Waren (brutto) 554,4 EUR  +
SUMME Versandkosten  (brutto) 23,42 EUR  
TOTAL = 577, 82 EUR (SOLLWERT)

PLUS 19% MwSt für Versandkosten 3,74 EUR
TOTAL = 581, 56 EUR (FALSCHER ANGEZEIGTER WERT)

**Comment by webchills** [comment]
fixed with 543ca95

**Comment by webchills** [comment]
Ein alter Fix hatte es nicht in 1.5.7 geschafft.
Das Problem ist, dass die Berechnung in Zeile 557 nicht für Shops geeignet ist, die Mehrwersteuer in den Versandkosten haben und das sollte ja in europäischen Shops Standard sein.
Ändere in DEINADMIN/includes/classes/sales_report.php ca. Zeile 557 auf:
`// line 557 may produce wrong totals for most European store configurations so we better use the line 558 below - if 557 works better for you than 558 change it
            // $order_total = ($order_goods + $order_recorded_tax + $order_shipping + $order_gc_sold) - ($order_discount + $order_gc_used);
            $order_total = ($order_goods + $order_goods_tax + $order_shipping + $order_gc_sold) - ($order_discount + $order_gc_used);`

behoben mit Commit 79b36bb
