### ISSUE TITLE
diverse undefined array key warnings

### ISSUE THREAD

**Issue by bumerang24** [zencartpro/zencart-german-grundsystem#18]
Hallo Webchills,

ich hoffe, ich schreibe nicht wieder, was das nicht passt.
Aber nach x Versuchen, leerer neuer Shop 157e, nur ein Artikel und nur Zahlung PayPal, kommen logs, und diese Geschichte hatte ich auch schon im Live Shop mit Erweiterungen.

[01-Dec-2022 19:59:50 Europe/Berlin] Request URI: /ipn_main_handler.php?type=ec&token=EC-PayerID=PUR, IP address: 62.
#1 paypalwpp->_errorHandler() called at [/includes/modules/payment/paypalwpp.php:1781]
#2 paypalwpp->ec_step2() called at [/ipn_main_handler.php:81]
--> PHP Warning: Undefined array key "customer_id" in /includes/modules/payment/paypalwpp.php on line 2889.

[01-Dec-2022 19:59:50 Europe/Berlin] Request URI: /ipn_main_handler.php?type=ec&token=EC-PayerID=PUR, IP address: 62.
#1 paypalwpp->_errorHandler() called at [/includes/modules/payment/paypalwpp.php:1781]
#2 paypalwpp->ec_step2() called at [/ipn_main_handler.php:81]
--> PHP Warning: Undefined array key "customer_first_name" in /includes/modules/payment/paypalwpp.php on line 2889.

[01-Dec-2022 19:59:50 Europe/Berlin] Request URI: /ipn_main_handler.php?type=ec&token=EC-PayerID=PUR IP address: 62.
#1 paypalwpp->_errorHandler() called at [/includes/modules/payment/paypalwpp.php:1781]
#2 paypalwpp->ec_step2() called at [/ipn_main_handler.php:81]
--> PHP Warning: Undefined array key "customer_last_name" in /includes/modules/payment/paypalwpp.php on line 2889.

[01-Dec-2022 19:59:50 Europe/Berlin] Request URI: /ipn_main_handler.php?type=ec&token=EC-PayerID=PUR, IP address: 62
#1 paypalwpp->ec_step2() called at [/ipn_main_handler.php:81]
--> PHP Warning: Undefined array key "shipping" in /includes/modules/payment/paypalwpp.php on line 1875.

[01-Dec-2022 19:59:50 Europe/Berlin] Request URI: /ipn_main_handler.php?type=ec&token=EC-PayerID=PUR, IP address: 62.
#1 ot_gv->__construct() called at [/includes/classes/order_total.php:52]
#2 order_total->__construct() called at [/includes/modules/payment/paypalwpp.php:1879]
#3 paypalwpp->ec_step2() called at [/ipn_main_handler.php:81]
--> PHP Warning: Undefined array key "customer_id" in /includes/modules/order_total/ot_gv.php on line 52.

[01-Dec-2022 19:59:50 Europe/Berlin] Request URI: /ipn_main_handler.php?type=ec&token=EC-PayerID=PUR IP address: 62.
#1 ot_group_pricing->calculate_deductions() called at [/includes/modules/order_total/ot_group_pricing.php:34]
#2 ot_group_pricing->process() called at [/includes/classes/order_total.php:179]
#3 order_total->pre_confirmation_check() called at [/includes/modules/payment/paypalwpp.php:1880]
#4 paypalwpp->ec_step2() called at [/ipn_main_handler.php:81]
--> PHP Warning: Undefined array key "customer_id" in /includes/modules/order_total/ot_group_pricing.php on line 89.

[01-Dec-2022 19:59:50 Europe/Berlin] Request URI: /ipn_main_handler.php?type=ec&token=EC-PayerID=PUR, IP address: 62.
#1 ot_group_pricing->calculate_deductions() called at [/includes/modules/order_total/ot_group_pricing.php:34]
#2 ot_group_pricing->process() called at [/includes/classes/order_total.php:179]
#3 order_total->pre_confirmation_check() called at [/includes/modules/payment/paypalwpp.php:1880]
#4 paypalwpp->ec_step2() called at [/ipn_main_handler.php:81]
--> PHP Warning: Undefined array key "customers_group_pricing" in /includes/modules/order_total/ot_group_pricing.php on line 90.

[01-Dec-2022 19:59:50 Europe/Berlin] Request URI: /ipn_main_handler.php?type=ec&token=EC-PayerID=PUR, IP address: 62.
#1 ot_group_pricing->calculate_deductions() called at [/includes/modules/order_total/ot_group_pricing.php:34]
#2 ot_group_pricing->process() called at [/includes/classes/order_total.php:179]
#3 order_total->pre_confirmation_check() called at [/includes/modules/payment/paypalwpp.php:1880]
#4 paypalwpp->ec_step2() called at [/ipn_main_handler.php:81]
--> PHP Warning: Undefined array key "customers_group_pricing" in /includes/modules/order_total/ot_group_pricing.php on line 92.

[01-Dec-2022 19:59:50 Europe/Berlin] Request URI: /ipn_main_handler.php?type=ec&token=EC-PayerID=PUR, IP address: 62.216.215.136
#1 ot_group_pricing->calculate_deductions() called at [/includes/modules/order_total/ot_group_pricing.php:34]
#2 ot_group_pricing->process() called at [/includes/classes/order_total.php:179]
#3 order_total->pre_confirmation_check() called at [/includes/modules/payment/paypalwpp.php:1880]
#4 paypalwpp->ec_step2() called at [/ipn_main_handler.php:81]
--> PHP Warning: Undefined array key "group_percentage" in /includes/modules/order_total/ot_group_pricing.php on line 94.

[01-Dec-2022 19:59:50 Europe/Berlin] Request URI: /ipn_main_handler.php?type=ec&token=EC-PayerID=PUR IP address: 62.
#1 ot_group_pricing->calculate_deductions() called at [/includes/modules/order_total/ot_group_pricing.php:34]
#2 ot_group_pricing->process() called at [/includes/classes/order_total.php:66]
#3 order_total->process() called at [/includes/modules/payment/paypalwpp.php:1881]
#4 paypalwpp->ec_step2() called at [/ipn_main_handler.php:81]
--> PHP Warning: Undefined array key "customer_id" in /includes/modules/order_total/ot_group_pricing.php on line 89.

[01-Dec-2022 19:59:50 Europe/Berlin] Request URI: /ipn_main_handler.php?type=ec&token=EC-PayerID=PUR IP address: 62.
#1 ot_group_pricing->calculate_deductions() called at [/includes/modules/order_total/ot_group_pricing.php:34]
#2 ot_group_pricing->process() called at [/includes/classes/order_total.php:66]
#3 order_total->process() called at [/includes/modules/payment/paypalwpp.php:1881]
#4 paypalwpp->ec_step2() called at [/ipn_main_handler.php:81]
--> PHP Warning: Undefined array key "customers_group_pricing" in /includes/modules/order_total/ot_group_pricing.php on line 90.

[01-Dec-2022 19:59:50 Europe/Berlin] Request URI: /ipn_main_handler.php?type=ec&token=EC-PayerID=PUR, IP address: 62.
#1 ot_group_pricing->calculate_deductions() called at [/includes/modules/order_total/ot_group_pricing.php:34]
#2 ot_group_pricing->process() called at [/includes/classes/order_total.php:66]
#3 order_total->process() called at [/includes/modules/payment/paypalwpp.php:1881]
#4 paypalwpp->ec_step2() called at [/ipn_main_handler.php:81]
--> PHP Warning: Undefined array key "customers_group_pricing" in /includes/modules/order_total/ot_group_pricing.php on line 92.

[01-Dec-2022 19:59:50 Europe/Berlin] Request URI: /ipn_main_handler.php?type=ec&token=EC-PayerID=, IP address: 62.2
#1 ot_group_pricing->calculate_deductions() called at [/includes/modules/order_total/ot_group_pricing.php:34]
#2 ot_group_pricing->process() called at [/includes/classes/order_total.php:66]
#3 order_total->process() called at [/includes/modules/payment/paypalwpp.php:1881]
#4 paypalwpp->ec_step2() called at [/ipn_main_handler.php:81]
--> PHP Warning: Undefined array key "group_percentage" in /includes/modules/order_total/ot_group_pricing.php on line 94.

[01-Dec-2022 19:59:50 Europe/Berlin] Request URI: /ipn_main_handler.php?type=ec&token=EC-PayerID=PUR IP address: 62.
#1 paypalwpp->ec_step2_finish() called at [/includes/modules/payment/paypalwpp.php:1888]
#2 paypalwpp->ec_step2() called at [/ipn_main_handler.php:81]
--> PHP Warning: Undefined array key "customer_default_address_id" in /includes/modules/payment/paypalwpp.php on line 1912.

[01-Dec-2022 19:59:50 Europe/Berlin] Request URI: /ipn_main_handler.php?type=ec&token=EC-PayerID=PUR, IP address: 62.
#1 paypalwpp->ec_step2_finish() called at [/includes/modules/payment/paypalwpp.php:1888]
#2 paypalwpp->ec_step2() called at [/ipn_main_handler.php:81]
--> PHP Warning: Undefined array key "paypal_ec_markflow" in /includes/modules/payment/paypalwpp.php on line 2270.

[01-Dec-2022 19:59:50 Europe/Berlin] Request URI: /ipn_main_handler.php?type=ec&token=EC-PayerID=PUR, IP address: 62.
#1 paypalwpp->terminateEC() called at [/includes/modules/payment/paypalwpp.php:2273]
#2 paypalwpp->ec_step2_finish() called at [/includes/modules/payment/paypalwpp.php:1888]
#3 paypalwpp->ec_step2() called at [/ipn_main_handler.php:81]
--> PHP Warning: Undefined array key "paypal_ec_markflow" in /includes/modules/payment/paypalwpp.php on line 2817.

und noch ein zweiter kleiner Log:

[01-Dec-2022 19:59:53 Europe/Berlin] Request URI: /index.php?main_page=checkout_payment, IP address: 62.
#1 require(/includes/templates/template_default/templates/tpl_checkout_payment_default.php) called at [/includes/templates/responsive_classic/common/tpl_main_page.php:179]
#2 require(/includes/templates/responsive_classic/common/tpl_main_page.php) called at [/index.php:95]
--> PHP Warning: Undefined array key "paypal_ec_markflow" in /includes/templates/template_default/templates/tpl_checkout_payment_default.php on line 204.

Template nicht VERÄNDERT, Sprachdatei nicht VERÄNDERT, English ausgeschaltet

**Comment by webchills** [comment]
Schau Dir die Commits der letzten Zeit an, sie kümmern sich fast alle um diese undefined key warnings:
https://github.com/zencartpro/zencart-german-grundsystem/commits/zc157

Hier alle Commits seit Release von 1.5.7e:
https://github.com/zencartpro/zencart-german-grundsystem/compare/v1.5.7e...zc157

Diese Dinge sind also bereits behoben und werden mit 1.5.7f auch in eine Release übernommen

Du kannst einfach das aktuelle Repository runterladen und die seit 1.5.7e geänderten Dateien mit Beyond Compare in Deinen Shop übernehmen, dann wird es auch dort diese Warnings nicht mehr geben

**Comment by bumerang24** [comment]
Vielen Dank für die Info, dann werde ich wohl weiterkämpfen müssen.

Bis 157f wird ja vermutlich noch etwas Zeit vergehen.

Ich muss derzeit leider eh noch meinen 156 Shop aufrechterhalten, weil nichts so will wie ich mir das vorstelle.

**Comment by webchills** [comment]
Noch zur Ergänzung: Keines dieser Logs ist ein Hinweis auf eine Fehlfunktion, der Shop und PayPal funktionieren problemlos. Unter PHP8 ist es mit der derzeitigen Codebasis nicht 100% möglich, solche Logs zu verhindern, die geposteten Commits verhindern aber schon jetzt fast alle noch verbleibenden. Generell mit PHP8 etwas toleranter mit Logfiles sein, nur die fatal errors sind wirklich ein Problem und die gibt es auch mit der 1.5.7e Release ohne die neuen Änderungen nicht.
Noch eine Bitte: Du verwendest immer die Antworten Funktion via Email, das ist schon ok, dann aber bitte dieses ganze Signaturzeug und Mailverlauf rauslöschen, das hat hier in den Issues auf Github nichts verloren. Danke.
