### ISSUE TITLE
Warning Logs durch Sidebox document_categories

### ISSUE THREAD

**Issue by 3dstc** [zencartpro/zencart-german-grundsystem#19]
Bekommen tausende logfiles mit dem Inhalt

Inhalt der Datei( /xxx/1/2/2/xxx/xxx/shop/logs/myDEBUG-20230122-101901-470185-warning.log)

[22-Jan-2023 10:19:01 UTC] Request URI: /shop/index.php?main_page=ask_a_question&pid=137, IP address: 85.25.185.103
#1 category_tree->zen_category_tree() called at [/includes/modules/sideboxes/document_categories.php:20]
#2 include(/includes/modules/sideboxes/document_categories.php) called at [/includes/modules/column_left.php:26]
#3 require(/includes/modules/column_left.php) called at [/includes/templates/responsive_classic/common/tpl_main_page.php:143]
#4 require(/includes/templates/responsive_classic/common/tpl_main_page.php) called at [/index.php:95]
--> PHP Warning: Undefined variable $first_element in /includes/classes/category_tree.php on line 142.

[22-Jan-2023 10:19:01 UTC] Request URI: /shop/index.php?main_page=ask_a_question&pid=137, IP address: 85.25.185.103
#1 category_tree->zen_show_category() called at [/includes/classes/category_tree.php:142]
#2 category_tree->zen_category_tree() called at [/includes/modules/sideboxes/document_categories.php:20]
#3 include(/includes/modules/sideboxes/document_categories.php) called at [/includes/modules/column_left.php:26]
#4 require(/includes/modules/column_left.php) called at [/includes/templates/responsive_classic/common/tpl_main_page.php:143]
#5 require(/includes/templates/responsive_classic/common/tpl_main_page.php) called at [/index.php:95]
--> PHP Warning: Undefined array key "" in /includes/classes/category_tree.php on line 150.

[22-Jan-2023 10:19:01 UTC] Request URI: /shop/index.php?main_page=ask_a_question&pid=137, IP address: 85.25.185.103
#1 category_tree->zen_show_category() called at [/includes/classes/category_tree.php:142]
#2 category_tree->zen_category_tree() called at [/includes/modules/sideboxes/document_categories.php:20]
#3 include(/includes/modules/sideboxes/document_categories.php) called at [/includes/modules/column_left.php:26]
#4 require(/includes/modules/column_left.php) called at [/includes/templates/responsive_classic/common/tpl_main_page.php:143]
#5 require(/includes/templates/responsive_classic/common/tpl_main_page.php) called at [/index.php:95]
--> PHP Warning: Trying to access array offset on value of type null in /includes/classes/category_tree.php on line 150.

[22-Jan-2023 10:19:01 UTC] Request URI: /shop/index.php?main_page=ask_a_question&pid=137, IP address: 85.25.185.103
#1 category_tree->zen_show_category() called at [/includes/classes/category_tree.php:142]
#2 category_tree->zen_category_tree() called at [/includes/modules/sideboxes/document_categories.php:20]
#3 include(/includes/modules/sideboxes/document_categories.php) called at [/includes/modules/column_left.php:26]
#4 require(/includes/modules/column_left.php) called at [/includes/templates/responsive_classic/common/tpl_main_page.php:143]
#5 require(/includes/templates/responsive_classic/common/tpl_main_page.php) called at [/index.php:95]
--> PHP Warning: Undefined array key "" in /includes/classes/category_tree.php on line 157.

[22-Jan-2023 10:19:01 UTC] Request URI: /shop/index.php?main_page=ask_a_question&pid=137, IP address: 85.25.185.103
#1 category_tree->zen_show_category() called at [/includes/classes/category_tree.php:142]
#2 category_tree->zen_category_tree() called at [/includes/modules/sideboxes/document_categories.php:20]
#3 include(/includes/modules/sideboxes/document_categories.php) called at [/includes/modules/column_left.php:26]
#4 require(/includes/modules/column_left.php) called at [/includes/templates/responsive_classic/common/tpl_main_page.php:143]
#5 require(/includes/templates/responsive_classic/common/tpl_main_page.php) called at [/index.php:95]
--> PHP Warning: Trying to access array offset on value of type null in /includes/classes/category_tree.php on line 157.

[22-Jan-2023 10:19:01 UTC] Request URI: /shop/index.php?main_page=ask_a_question&pid=137, IP address: 85.25.185.103
#1 category_tree->zen_show_category() called at [/includes/classes/category_tree.php:142]
#2 category_tree->zen_category_tree() called at [/includes/modules/sideboxes/document_categories.php:20]
#3 include(/includes/modules/sideboxes/document_categories.php) called at [/includes/modules/column_left.php:26]
#4 require(/includes/modules/column_left.php) called at [/includes/templates/responsive_classic/common/tpl_main_page.php:143]
#5 require(/includes/templates/responsive_classic/common/tpl_main_page.php) called at [/index.php:95]
--> PHP Warning: Undefined array key "" in /includes/classes/category_tree.php on line 174.

[22-Jan-2023 10:19:01 UTC] Request URI: /shop/index.php?main_page=ask_a_question&pid=137, IP address: 85.25.185.103
#1 category_tree->zen_show_category() called at [/includes/classes/category_tree.php:142]
#2 category_tree->zen_category_tree() called at [/includes/modules/sideboxes/document_categories.php:20]
#3 include(/includes/modules/sideboxes/document_categories.php) called at [/includes/modules/column_left.php:26]
#4 require(/includes/modules/column_left.php) called at [/includes/templates/responsive_classic/common/tpl_main_page.php:143]
#5 require(/includes/templates/responsive_classic/common/tpl_main_page.php) called at [/index.php:95]
--> PHP Warning: Trying to access array offset on value of type null in /includes/classes/category_tree.php on line 174.

[22-Jan-2023 10:19:01 UTC] Request URI: /shop/index.php?main_page=ask_a_question&pid=137, IP address: 85.25.185.103
#1 category_tree->zen_show_category() called at [/includes/classes/category_tree.php:142]
#2 category_tree->zen_category_tree() called at [/includes/modules/sideboxes/document_categories.php:20]
#3 include(/includes/modules/sideboxes/document_categories.php) called at [/includes/modules/column_left.php:26]
#4 require(/includes/modules/column_left.php) called at [/includes/templates/responsive_classic/common/tpl_main_page.php:143]
#5 require(/includes/templates/responsive_classic/common/tpl_main_page.php) called at [/index.php:95]
--> PHP Warning: Undefined array key "" in /includes/classes/category_tree.php on line 177.

[22-Jan-2023 10:19:01 UTC] Request URI: /shop/index.php?main_page=ask_a_question&pid=137, IP address: 85.25.185.103
#1 category_tree->zen_show_category() called at [/includes/classes/category_tree.php:142]
#2 category_tree->zen_category_tree() called at [/includes/modules/sideboxes/document_categories.php:20]
#3 include(/includes/modules/sideboxes/document_categories.php) called at [/includes/modules/column_left.php:26]
#4 require(/includes/modules/column_left.php) called at [/includes/templates/responsive_classic/common/tpl_main_page.php:143]
#5 require(/includes/templates/responsive_classic/common/tpl_main_page.php) called at [/index.php:95]
--> PHP Warning: Trying to access array offset on value of type null in /includes/classes/category_tree.php on line 177.

[22-Jan-2023 10:19:01 UTC] Request URI: /shop/index.php?main_page=ask_a_question&pid=137, IP address: 85.25.185.103
#1 category_tree->zen_show_category() called at [/includes/classes/category_tree.php:142]
#2 category_tree->zen_category_tree() called at [/includes/modules/sideboxes/document_categories.php:20]
#3 include(/includes/modules/sideboxes/document_categories.php) called at [/includes/modules/column_left.php:26]
#4 require(/includes/modules/column_left.php) called at [/includes/templates/responsive_classic/common/tpl_main_page.php:143]
#5 require(/includes/templates/responsive_classic/common/tpl_main_page.php) called at [/index.php:95]
--> PHP Warning: Undefined array key "" in /includes/classes/category_tree.php on line 194.

[22-Jan-2023 10:19:01 UTC] Request URI: /shop/index.php?main_page=ask_a_question&pid=137, IP address: 85.25.185.103
#1 category_tree->zen_show_category() called at [/includes/classes/category_tree.php:142]
#2 category_tree->zen_category_tree() called at [/includes/modules/sideboxes/document_categories.php:20]
#3 include(/includes/modules/sideboxes/document_categories.php) called at [/includes/modules/column_left.php:26]
#4 require(/includes/modules/column_left.php) called at [/includes/templates/responsive_classic/common/tpl_main_page.php:143]
#5 require(/includes/templates/responsive_classic/common/tpl_main_page.php) called at [/index.php:95]
--> PHP Warning: Trying to access array offset on value of type null in /includes/classes/category_tree.php on line 194.

wo liegt der Fehler??

**Comment by webchills** [comment]
Vorweg: Diese Logfiles weisen nicht auf irgendwelche echten Fehlfunktionen hin:
https://www.zen-cart-pro.at/knowledgebase/bedeutung-von-notice-warning-und-error-in-den-zen-cart-debug-logs/

Gibt es in diesem Shop überhaupt irgendwelche Kategorien?
Gibt es in diesem Shop Artikel vom Typ Dokumente?
Wird die Sidebox document_categories.php daher überhaupt benötigt?

**Comment by 3dstc** [comment]
gewerbefoto-wildau.de/shop

**Comment by webchills** [comment]
In diesem Shop kann es aktuell keine solchen Logs mit Bezug auf sideboxes/document_categories.php geben.
Inhalt des Ordners logs löschen.
Falls es danach bei Aufruf von gewerbefoto-wildau.de/shop/index.php?main_page=ask_a_question&pid=137 noch irgendwelche Logfiles geben sollte, Inhalt hier posten. Echte Serverpfade durch xxx ersetzen.
