### ISSUE TITLE
Service not available mit PHP 8.0.27

### ISSUE THREAD

**Issue by webconcept-one** [zencartpro/zencart-german-grundsystem#20]
Die Installation funktioniert unter 8.0.27, jedoch erscheint nach der Installation "Service not available".
Ein Wechsel auf 7.4.33 behebt das Problem.
Wird anschließend wieder zurück auf 8.0.27 gewechselt, dann funktioniert alles einwandfrei.
Alles mehrfach wiederholt.

**Comment by webchills** [comment]
Welche Seite genau liefert nach der Installation "Service not available". Was steht da genau in der Adresszeile?

**Comment by webconcept-one** [comment]
Shop Startseite
und
Admin Startseite

**Comment by webchills** [comment]
Die Shop Startseite und die Admin Startseite sind weiss.
Das ist nicht normal und kann nirgends unter PHP 8.0.x nachvollzogen werden.
Bei einer weissen Seite muss es ein Logfile geben, immer so vorgehen wie hier beschrieben:
https://www.zen-cart-pro.at/knowledgebase/weisse-seite-an-error-occured-datenbankabfragen-schlagen-fehl/
Überprüfe Deine Error Logs, sie werden zeigen was hier faul ist.
Sollte es kein Logfile geben, prüfen ob das providerseitig überhaupt aktiv ist:
https://www.zen-cart-pro.at/knowledgebase/trotz-sicherer-fehler-werden-beim-provider-host-europe-keine-error-logs-geschrieben/

**Comment by webconcept-one** [comment]
Ich sehe keine weiße Seite (a la BOM), sondern einen HTTP Fehler.

Es ist eine frische Installation.

Im Unterverzeichnis logs finde ich regelmäßig folgende Fehlermeldung:

```
[08-Apr-2023 12:36:17 Europe/Berlin] PHP Warning:  Undefined variable $_SESSION in /home/users/roller/www/github/includes/extra_configures/enable_error_logging.php on line>
[08-Apr-2023 12:36:17 Europe/Berlin] PHP Warning:  Trying to access array offset on value of type null in /home/users/roller/www/github/includes/extra_configures/enable_er>
[08-Apr-2023 12:36:17 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function error_log() in /home/users/roller/www/github/includes/extra_configures/en>
Stack trace:
#0 [internal function]: zen_debug_error_handler()
#1 /home/users/roller/www/github/includes/functions/sessions.php(165): session_save_path()
#2 /home/users/roller/www/github/includes/init_includes/init_sessions.php(33): zen_session_save_path()
#3 /home/users/roller/www/github/includes/autoload_func.php(39): require_once('...')
#4 /home/users/roller/www/github/includes/application_top.php(213): require('...')
#5 /home/users/roller/www/github/index.php(26): require('...')
#6 {main}
  thrown in /home/users/roller/www/github/includes/extra_configures/enable_error_logging.php on line 91
[08-Apr-2023 12:36:17 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function error_log() in /home/users/roller/www/github/includes/extra_configures/en>
Stack trace:
#0 [internal function]: zen_fatal_error_handler()
#1 {main}
  thrown in /home/users/roller/www/github/includes/extra_configures/enable_error_logging.php on line 104
```

**Comment by webchills** [comment]
Das Log zeigt einen Fatal Error, daher wird die Verarbeitung der Seite unter PHP 8 abgebrochen.
PHP 8 ist hier wesentlich strikter.
Chrome zeigt in solchen Fällen "Diese Seite funktioniert nicht"
Firefox zeigt eine weiße Seite.
Unter PHP 7 wird die Ausführung nicht abgebrochen, deshalb erscheint dann die Seite obwohl etwas grundfaul ist.
Überprüfe ob Du wirklich alle Dateien korrekt hochgeladen hast, 99,9% solcher Fehler liegen an unvollständig übertragenen Dateien.
Wird alles vollständig und korrekt hochgeladen, gibt es dieses Problem definitiv nicht.

**Comment by webconcept-one** [comment]
Ich habe alles aus UPLOAD hochgeladen und auf dem Server entpackt.
Ich habe das verwendete UPLOAD Verzeichnis mit einem erneut von der Homepage heruntergeladenen UPLOAD Verzeichnis, sowie dem UPLOAD Verzeichnis auf github verglichen. Es ist identisch.

Der Installer macht seine Arbeit perfekt, nur dann ist halt Schluss.

"Wird alles vollständig und korrekt hochgeladen, gibt es dieses Problem definitiv nicht."
Da muss ich dir widersprechen. Das stimmt so einfach nicht.
