### ISSUE TITLE
PHP Warning: Undefined variable $email_text in /includes/modules/create_account.php

### ISSUE THREAD

**Issue by webconcept-one** [zencartpro/zencart-german-grundsystem#23]
[15-May-2023 11:27:24 Europe/Berlin] Request URI: /index.php?main_page=create_account, IP address: 2003:d4:cf0f:ec85:bcfa:eadd:3c0c:6e69, Language id 43
#1 include(/includes/modules/create_account.php) called at [/includes/modules/pages/create_account/header_php.php:18]
#2 require(/includes/modules/pages/create_account/header_php.php) called at [/index.php:36]
--> PHP Warning: Undefined variable $email_text in /includes/modules/create_account.php on line 384.

**Comment by webchills** [comment]
Posting just a logfile without any additional info is useless and in fact quite rude. There is no such logfile when creating an account in a vanilla 1.5.7f installation. So you seem to have integrated a module or more. If you have an issue with a module report it in the issues of the appropriate module repository and not here. And post at least what you do when such a log occurs and what you have done before, your PHP version, etc. etc.
