### ISSUE TITLE
Fehler bei Aufruf der Rechnung unter "Mein Konto"

### ISSUE THREAD

**Issue by webconcept-one** [zencartpro/zencart-german-grundsystem#24]
Während PDF Rechnungen grundsätzlich korrekt erstellt werden, führt ein Aufruf als Kunde unter Mein Konto zu einem Fehler.
zc 157f
php 8.0.28

Die Browsermeldung (Chromium) lautet:

```
This site can’t be reached
The webpage at https://www.beispiel.de/index.php?main_page=rl_invoice3&fn=838_dfc4f653a19d6aec55c224d08c5c6ba8.pdf&order=838 might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE
```
In den Logs ist folgender Eintrag zu finden:

```
[13-Jun-2023 10:25:07 Europe/Berlin] Request URI: /index.php?main_page=rl_invoice3&fn=838_dfc4f653a19d6aec55c224d08c5c6ba8.pdf&order=838, IP address: 2a02:8108:94c0:27a0:abab:2630:2428:782e
--> PHP Fatal error: Uncaught Error: Call to undefined function symlink() in /includes/modules/pages/rl_invoice3/header_php.php:103
Stack trace:
#0 /index.php(36): require()
#1 {main}
thrown in /includes/modules/pages/rl_invoice3/header_php.php on line 103.
```

**Comment by webchills** [comment]
Es wird die PHP Funktion symlink benötigt.
https://www.php.net/manual/en/function.symlink.php
Die ist auch in PHP 8 enthalten, scheint bei Deinem Provider aber deaktiviert zu sein.

Datei namens test.php erstellen mit folgendem Inhalt:
`<?php
var_dump(function_exists('symlink'));`

Hochladen ins Shopverzeichnis und im Browser aufrufen

Bei den meisten Providern wir das Ergebnis true sein
Bei Dir wohl false

>>> Provider kontaktieren oder falls Root Zugriff besteht, symlink selbst in PHP erlauben/aktivieren

**Comment by webconcept-one** [comment]
Das stimmt,
das war deaktiviert.
Jetzt wird allerdings das pub Verzeichnis aufgerufen mit folgender Fehlermedung
/pub/.mrmitzbfksivlrkeeo/rechnung.pdf

```
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@beispiel.de to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
```

Es wird kein error log mehr geschrieben.

Die erzeugten Rechnungen liegen aber ausserhalb des Webserververzeichnis unter ~files/PDF/
Das sieht im zc Backend auch okay aus so. Fuunktionierte mit älteren zc Versionen und PHP 7 auch immer unauffällig.

**Comment by webchills** [comment]
Es hat sich gegenüber früheren Version bei der pdf Rechnung an dieser Funktionalität nichts geändert.
Du musst unter Konfiguration > Attributeinstellungen > Downloads über Weiterleitung auf false stellen.
Ausführliche Infos zur Konfiguration der pdf Rechnung hier:
https://www.zen-cart-pro.at/knowledgebase/pdf-rechnung/

**Comment by webconcept-one** [comment]
Genau die notwendige Einstellung.
Vielen Dank!
