### ISSUE TITLE
Sortierung in Wer ist online verursacht Redirect auf Admin Startseite

### ISSUE THREAD

**Issue by webconcept-one** [zencartpro/zencart-german-grundsystem#30]
Ein Klick in "wer ist online" auf Toggle zur Sortierung verursacht bei mir einen Redirect auf die Admin Startseite.

Installiert als Update von 157f
MySQL 10.11.4-MariaDB-1~deb12u1
PHP 8.1.24
Ein Logeintrag ist nicht vorhanden.

**Comment by webchills** [comment]
Kann ich nicht nachvollziehen. Sind DEINADMIN/whos_online.php und DEINADMIN/includes/classes/WhosOnline.php wirklich auf dem Stand der aktuellen 1.5.7g vom 12.12.23?

**Comment by webconcept-one** [comment]
Ja, habe ich gerade überprüft.
Beide 2023.12.12

Ich mache später, wenn ich mit dem Gröbsten durch bin - oder morgen - parallel mal ein Fresh Install

**Comment by webchills** [comment]
Was genau bedeutet "Click auf einen beliebigen Filter"?
https://demo.zen-cart-pro.at/chefe/index.php?cmd=whos_online
Wo clickst Du da genau hin?

**Comment by webconcept-one** [comment]
Sortierung wäre wohl der treffende Begriff gewesen.
![2023-12-17-144453_1920x1080_scrot](https://github.com/zencartpro/zencart-german-grundsystem/assets/23481663/8f77015b-c835-48cf-8b1c-d6a2e0af36e7)

PS: Im Demoshop erhalte ich bei Klick auf einern Toggle zur Sortierung die folgende Fehlermeldung:

> Entschuldigung, aber Sie haben keine Zugangsberechtigung zu diesem Bereich.
> Für den Erhalt einer fehlenden Zugangsberechtigung oder die Überprüfung ihrer Zugangsberechtigungen nehmen Sie bitte mit den Shop Administrator Kontakt auf.
> Entschuldigen Sie die Unannehmlichkeiten.
>

**Comment by webchills** [comment]
fixed with 3e76ac6bcfc6fa2ce41c68fc32698caa97b76a9b
