### ISSUE TITLE
PHP Fatal error: Uncaught Error: Found unconstructed IntlDateFormatter in /includes/classes/zcDate.php:95

### ISSUE THREAD

**Issue by webconcept-one** [zencartpro/zencart-german-grundsystem#32]
Server Error 500 mit PHP >=8.1.25

zc 157g

Ein Fallback auf PHP 8.0.30 macht den Shop wieder aufrufbar, erzeugt aber haufenweise Fatal Error.

Workaround: Hinzufügen der folgenden Zeile in includes/configure.php **und** <admin>/includes/configure.php

@setlocale(LC_TIME, ['de_DE', 'de_DE.UTF-8', 'de-DE']);

**Comment by webchills** [comment]
Auf diesem Server scheint keine default locale konfiguriert zu sein oder eine sonstige locale Fehlkonfiguration des Providers vorzuliegen.
Welche locales überhaupt verfügbar sind, kann mit dem Script extras/check_server_locales.php im Ordner TOOLS ermittelt werden.
Besser als diese Änderungen in den configure.php ist, solche Serverseltsamkeiten abzufangen. Der folgende Commit nimmt dazu die entsprechenden Änderungen vor:
7d1733f7ea3adc94b87574993c2cb6334309b4ee
Bitte mal diese Dateien einspielen und die Änderungen in den configure rückgängig machen.
Bitte um Info, ob es danach auch auf diesem Server ok ist.

**Comment by webconcept-one** [comment]
Es sind default locales für DE und US eingerichtet.
Ich teste die geänderten Dateien im Laufe des Tages.

```
$ locale -a
C
C.utf8
de_DE.utf8
en_US.utf8
POSIX
```

PS: Das Skript zeigt das auch so an.

**Comment by webconcept-one** [comment]
Das funktioniert!
