### ISSUE TITLE
Darstellungsfehler nach Entfernen der includes\templates\responsive_classic\templates\tpl_advanced_search_result_default.php

### ISSUE THREAD

**Issue by webconcept-one** [zencartpro/zencart-german-grundsystem#33]
Ich habe nach dem Update von 157f auf 157g (und dem Entfernen der o.g. Template Datei) den Darstellungsfehler, dass der Filter für "Artikelname, beginnend mit ..." nicht mehr, wie vorab, über .filter-wrapper gestaltet werden kann.

Das Design weicht somit ab von den anderen Listendarstellungen.

**edit: Das Wiedereinspielen aus dem 157f Backup behebt den Darstellungsfehler.**

Wie sollte man damit umgehen?
Sollte ich wegen so etwas bei den Amerikanern fragen?

![157f](https://github.com/zencartpro/zencart-german-grundsystem/assets/23481663/43e765f3-0bb7-4b74-ad71-e93e8d85305b)
![157g](https://github.com/zencartpro/zencart-german-grundsystem/assets/23481663/fb6e637c-e009-4f3f-83ae-d48a49e931a2)
![157g-all](https://github.com/zencartpro/zencart-german-grundsystem/assets/23481663/e5caaae5-21ea-4381-8d91-169cc5d11406)

**Comment by webchills** [comment]
Datei hat gefehlt, hätte nicht gelöscht werden sollen.
Fixed with 723f550e935a4bf79c20bb1b2b0e71a0d6bb1d1f
