### ISSUE TITLE
Leere col150 in responsive_classic nach Deaktivierung von Sidebox

### ISSUE THREAD

**Issue by webconcept-one** [zencartpro/zencart-german-grundsystem#35]
Auf einer Testinstallation hatte ich kurz eine Sidebox aktiviert.
Nach anschließender Deaktivierung wird der Layoutbereich nicht mehr freigegeben.
Anstatt von col970 werden seitdem col820 und col150 geladen.
Alle Versuche der Zurücksetzens über admin->tools->boxlayout sind gescheitert.

**Comment by webchills** [comment]
Tools > Boxlayout aktiviert/deaktiviert lediglich die Sideboxen und legt deren Reihenfolge fest. Ob rechte und linke Sidebar überhaupt angezeigt werden und Breite der Sidebar und Boxen ist davon völlig unabhängig unter Konfiguration > Layouteinstellungen einzustellen.

**Comment by webconcept-one** [comment]
Danke, es war -> Konfiguration > Layouteinstellungen -> "linke Spaltenansicht - Global"
