### ISSUE TITLE
Undefined variable $loaders in /extras/plugins/riCjLoader/RiCjLoaderPlugin.php

### ISSUE THREAD

**Issue by Anton2024tf** [zencartpro/zencart-german-grundsystem#44]
Ich hab die neuste Grundversion vom 15.4. installiert, die problemlos funktionierte, und dann gemäß Anleitung ein Update von Version 1.5.5f auf die jetzige Version gemacht. Ich wäre dankbar für Hilfe, wie ich folgdene Fehlermeldung in den Logfiles beheben kann. Bei jedem Aufruf des Shops gibt es eine neue solche Meldung:

#0 /extras/plugins/riCjLoader/RiCjLoaderPlugin.php(88): zen_debug_error_handler()
#1 /includes/templates/template_default/common/html_header.php(97): RiCjLoaderPlugin->autoloadLoaders()
#2 /index.php(43): require('...')
--> PHP Warning: Undefined variable $loaders in /extras/plugins/riCjLoader/RiCjLoaderPlugin.php on line 88.
--> PHP Warning: Undefined variable $loaders in /extras/plugins/riCjLoader/RiCjLoaderPlugin.php on line 88.

**Comment by webchills** [comment]
Kann auftreten, wenn andere Templates als responsive_classic verwendet werden.
Damit das für alle Templates passt ändere in in extras/plugins/riCjLoader/RiCjLoaderPlugin.php Zeile 88 von
`if(is_array($loaders) && count($loaders) > 0)	$this->addLoaders($loaders, true);`
auf:
`if(!empty($loaders))	$this->addLoaders($loaders, true);`
Damit wird dieses Log verschwinden. Bitte kurz bestätigen, ob dem so ist.

**Comment by Anton2024tf** [comment]
Super! Das hat geklappt. Die Meldung taucht nicht mehr auf. Ich hatte damals das Template Winchester Black und hab jetzt nach dieser Änderung auch umgestellt auf Responsive Classic.
Vielen Dank!

**Comment by webchills** [comment]
fixed with c72afe9f626f8726fdd6ab44800e179804eb7736
