### ISSUE TITLE
Verlinken in andere Kategorie funktioniert nicht

### ISSUE THREAD

**Issue by webconcept-one** [zencartpro/zencart-german-grundsystem#47]
Das Verlinken eines Artikels über den "C" Button funktioniert nicht (mehr).
Nach der Auswahl der zu verlinkenden Kategorie landet man nach der Bestätigung in der Hauptkategorie.
Der Artikel wird nicht verlinkt. Leider kein Logfile vorhanden.
Ich konnte mir mit dem Link Manager behelfen, der weiterhin zuverlässig arbeitet.

PS: vor einigen Monaten hatte ich zwischendurchQuickedit installiert - und ich meine - auch korrekt wieder deinstalliert.

**Comment by webchills** [comment]
Nicht nachvollziehbar, probiere es einfach im Demoshop mal aus. Macht genau das, was es soll.

**Comment by out-of-order** [comment]
Ok,
ich selber komme mit dem Workaround auch erst einmal zurecht.

**Comment by webconcept-one** [comment]
Ok,
in meinem Fall scheint es sich um ein Problem mit einer ungültigen Kategorie ID zu handeln.
Denn nicht alle Artikel sind davon betroffen.
Vor einiger Zeit habe ich Unterkategorien restrukturiert und in diesem Zusammenhang Artikel verschoben.
Zwar sind alle Artikel wieder korrekt einer oder mehreren gültigen Kategorien zugewiesen, dennoch scheinen eben nur diese Artikel von dem Problem betroffen zu sein.

**Comment by webchills** [comment]
Du solltest unter Tools > Shop Manager mal die Funktion Alle Hauptkategorie IDs zurücksetzen ausführen, um solche Datenbankprobleme zu beheben.
