### ISSUE TITLE
Borrow translation for installation

### ISSUE THREAD

**Issue by Zen4All** [zencartpro/zencart-german-grundsystem#5]
Hi,
I am working on the multi-lingual installer for the new Zen Cart 1.5.7 see https://github.com/zencart/zencart/issues/3018 , an I was wondering if it is okay with you if I used your german tranlation from file /zc_install/includes/languages/lngDeutsch.php for this

**Comment by webchills** [comment]
Of course, feel free to use it

**Comment by Zen4All** [comment]
thanks
