### ISSUE TITLE
Keine Zeilenumbrüche im E-Mail des Kontaktformulares

### ISSUE THREAD

**Issue by Hard-Virus** [zencartpro/zencart-german-grundsystem#54]
Hallo,
nun es ist zwar sicherlich kein Fehler, aber vielleicht hilft es ja dem einen oder anderen weiter:

Wie kann man die Entfernung der Zeilenumbrüche in der **$EMAIL_MESSAGE_HTML** entfernen. 
Mir ist aufgefallen, dass sämtliche Umbrüche im eigentlich Text aus den Mails aus dem Kontaktformular heraus entfernt und dieser Text dann in einer durchgehenden "Wurst" angezeigt werden.

Finde in der **mail.php** nichts entsprechendes, genausowenig in der **functions_email.php** ...

Über Hilfe würde ich mich sehr freuen.

**Comment by webchills** [comment]
Mails über das Kontaktformular sind als Text Mails vorgesehen und in diesen Textmails werden diese Umbrüche nicht entfernt und korrekt so wie sie geschrieben wurden im Textmail angezeigt. Das Mail über das Kontaktformular sollte nie als HTML Mail kommen, das wäre auch ziemlich sinnlos, jedesmal das Shoplogo und das Layout des Shops für ein Mail, das nicht an Kunden geht. So ist es auch viel einfacher auf das Mail zu antworten. Ebenso ist es mit den Lagerbestandwarnungsmails.

Wenn bei Dir das Kontaktformularmail als HTML Mail kommt, dann hat die Email des Kontaktformularempfängers (Einstellungen > Email Einstellungen > Emailadresse (Kontaktadresse)) auch einen normalen Kundenaccount im Shop und die Emaileinstellungen dieses Kunden sind auf HTML gesetzt. Stelle diesen Kunden auf Text Emails um und sende dann das Kontaktformular nochmal ab, dann siehst Du den Unterschied und das Mail kommt so wie es gedacht ist mit den Umbrüchen.
Ändere die Email dieses Testkunden auf eine andere ab, die nicht die Deines Shopadministrators ist. Der Shopadmin oder der Empfänger des Kontaktmails sollten keinen normalen Kundenaccount im Shop haben.

**Comment by Hard-Virus** [comment]
Ah ok verstehe. 
Die Empfängeradresse des Shopadmin und gleichzeitig als Kundenaccount-Mailadresse passierte nur zu reinen Testzwecken für den Mailempfang. Aus dem Grund entstand ja auch meine Frage heraus.
Danke für die Aufklärung ...
